### ISSUE TITLE
不知道为什么无法在mac上使用

### ISSUE THREAD

**Issue by czhmisaka** [2984539695/Crosstalk-rainbow-fart#2]
# 环境
MacBook Pro（14英寸，2021年）- 12.0.1 (21A559) - Apple M1 Pro

可能是wav格式的问题?

**Comment by Weidows** [comment]
😵这两天我给搞搞试试

**Comment by czhmisaka** [comment]
感谢大佬,我这里查看好像是因为音频格式问题



在 2022-03-03 21:14:47，"齐下无贰" ***@***.***> 写道：

😵这两天我给搞搞试试

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Weidows** [comment]
发给你邮件了 czh2233445566@163.com 可以帮忙试试吗 @czhmisaka

**Comment by Weidows** [comment]
更新了, 有空的话可以试试行不行😘

**Comment by czhmisaka** [comment]
好用啦 🤣

**Comment by Weidows** [comment]
好的谢谢反馈,有问题欢迎再来提😘
